### ISSUE TITLE
Bash doesn't compile on arch linux.

### ISSUE THREAD

**Issue by kubast2** [leleliu008/ndk-pkg-formula#2]
```
ld: error: duplicate symbol: strchrnul
>>> defined at strchrnul.c
>>>            strchrnul.o:(strchrnul) in archive ./lib/sh/libsh.a
>>> defined at static_function_dispatch.S:39 (bionic/libc/arch-arm64/static_function_dispatch.S:39)
>>>            static_function_dispatch.o:(.text+0x30) in archive /home/kubast2/Android/Sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21/libc.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:582: bash] Error 1
make: Leaving directory '/tmp/tmp.yDkXKIKWcs/1625446615/arm64-v8a'
[✘] install bash/arm64-v8a failed! you can go to /tmp/tmp.yDkXKIKWcs to see see.
```
/tmp/tmp.yDkXKIKWcs
[test.tar.gz](https://github.com/leleliu008/ndk-pkg-formula/files/6760922/test.tar.gz)

**Comment by leleliu008** [comment]
this is a issue since android-ndk r22 : https://github.com/android/ndk/issues/1409, please using android-ndk r21

**Comment by kubast2** [comment]
I will take a look at that.

``Between r21d and r22, the upstream Clang driver changed its default from -fcommon to -fno-common``

Can you try adding ``-fcommon`` flag somewhere in the CFLAGS? If it really is about that, which I doubt.

But from I can tell the function from libsh appears in bionic libc for android 21(5.0).

**Comment by leleliu008** [comment]
`-fcommon` added in CFLAGS, yet same error.

**Comment by kubast2** [comment]
That's because the libc.a static bionic library, contains the same symbol strchrnul.

The way to respond to something like this can be:
1.Unpack the static library archive(it is made with ar) and contains .o files put in it blindly. Remove the offending .o file, and let libsh use said symbol, the static library(ar archive) modification needs to be local. And then we make sure it finds our new static libc first before one found in ndk.
Because such change isn't done to a shared library there are no side effects to this.
2.Remove the function from libsh, it is just a single file, but it would take a whole lot more time, there might be side effects if the bionic libc implementation has a different behavior.

**Comment by leleliu008** [comment]
remove `--enable-static-link`, using shared library, don't use static library.

**Comment by kubast2** [comment]
Yeah the armv7 build didn't went through for ndk22 and ndk21

ndk22 and 21 didn't find a couple of libc wrappers to setgrent getgrent endgrent;
and it also has an undefined reference to mblen;

Both disabling static link and modifying the library worked fine.
But I can agree ``--enable-static-link`` would be a whole lot more clean.
Than this:
```
    mkdir ../temp_lib
    cp $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/$NATIVE_OS_KIND-$NATIVE_OS_ARCH/sysroot/usr/lib/$TARGET_TRIPLE2/$TARGET_OS_VERS/libc.a lmao/libc.a
    ar d strchrnul.o libc.a
    export CFLAGS="-L $(pwd)/../temp_lib $CFLAGS"
    configure \
        --with-curses \
        --without-bash-malloc \
        --disable-profiling \
        --enable-readline \
        --enable-select \
        --enable-history
        --enable-static-link
```

At least from my end how can I ignore armv7 builds?

**Comment by leleliu008** [comment]
```
case $TARGET_OS_ARCH in
        armv7a)
           
            ;;
        aarch64)
            
            ;;
        i686)
           
            ;;
        x86_64)
            
            ;;
    esac
```

**Comment by kubast2** [comment]
> ```
> case $TARGET_OS_ARCH in
>         armv7a)
>            
>             ;;
>         aarch64)
>             
>             ;;
>         i686)
>            
>             ;;
>         x86_64)
>             
>             ;;
>     esac
> ```

Fair I should have thought of that

**Comment by kubast2** [comment]
Well the issue is closed for me, but you will probably want the armv7a running

**Comment by leleliu008** [comment]
android-ndk r21 is highly recommended. because it is used in my Github Actions CI.

**Comment by kubast2** [comment]
.c ```c
        #include <sys/types.h>
        #include <grp.h>
        struct group* getgrent(void) {
                return NULL;
        }
        void setgrent(void) {
                return;
        }
        void endgrent(void) {
                return;
``` .h ```c
        struct group* getgrent(void);
        void setgrent(void);
        void endgrent(void);
```

**Comment by kubast2** [comment]
fails for me with ndk 21 as well actually
idk what made it jump from aarch64 build to armv7 build

**Comment by kubast2** [comment]
```xml
<kubast2>       Hey, how crucial is setgrent, getgrent and endgrent for bash? Say the target system doesn't have /etc/group, can I make a thin wrapper that will just return the error condition?
<kubast2>       I will just verify
 <kubast2>       setgrent(3) getgrent(3) endgrent(3) is usually part of libc; but I have this specific embedded application with some alternative libc; which comes without those functions;
 <earnestly>     Appears to use it directly for group name completions, and only there
```

**Comment by kubast2** [comment]
I can also just disable bash-autocompletion because I won't be interacting with bash directly

**Comment by leleliu008** [comment]
They are introduced in `android-26`.
